version: '3.8'

services:
  # Code Server
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    user: "1001:1001"
    environment:
      - PASSWORD=123456
      - CODE_SERVER_BASE_PATH=/code
    volumes:
      - ./nextcloud/html/data/lcmonitor/files/Code:/home/coder
      - ./code-server/config:/home/coder/.config/code-server
    networks:
      - app-network
    restart: unless-stopped
    command: --bind-addr 0.0.0.0:8080

  # Nextcloud
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    volumes:
      - ./nextcloud/html:/var/www/html
    networks:
      - app-network
    restart: unless-stopped

  # Nginx（反向代理）
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d 
      - /etc/letsencrypt:/etc/letsencrypt  
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - code-server
      - nextcloud
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=123456
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - app-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
    networks:
      - app-network

  wikijs:
    image: ghcr.io/requarks/wiki:latest
    container_name: wikijs
    ports:
      - "3030:3000"  # 可通过 localhost:3030 访问
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=wikijs
      - DB_PASS=123456
      - DB_NAME=wikidb
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./nextcloud/html/data/monitor/files/wiki:/wiki/data/repo
      - ./wikijs/config.yml:/wiki/config.yml:ro
networks:
  app-network:
    driver: bridge
