services:
  # Code Server
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    user: "33:33"
    environment:
      - PASSWORD=123456
      - CODE_SERVER_BASE_PATH=/code
    volumes:
      - ./nextcloud/html/data/codeserver/files:/home/coder
      - ./code-server/config:/home/coder/.config/code-server
      - ./code-server/data/www:/var/www
    networks:
      - app-network
    restart: unless-stopped
    command: --bind-addr 0.0.0.0:8080

  # Nextcloud
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    volumes:
      - ./nextcloud/html:/var/www/html
    networks:
      - app-network
    restart: unless-stopped

  # Nginx（反向代理）
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d 
      - /etc/letsencrypt:/etc/letsencrypt  
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - code-server
      - nextcloud
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=123456
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - app-network

  netdata:
    image: netdata/netdata:latest
    container_name: netdata
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./netdata/config:/etc/netdata
      - ./netdata/lib:/var/lib/netdata
      - ./netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
    networks:
      - app-network

  wikijs:
    image: ghcr.io/requarks/wiki:latest
    container_name: wikijs
    user: "33:33"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=wikijs
      - DB_PASS=123456
      - DB_NAME=wikidb
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./nextcloud/html/data/wikijs/files:/wiki/data/
      - ./wikijs/config.yml:/wiki/config.yml:ro
networks:
  app-network:
    driver: bridge
