version: '3.8'

services:
  # Code Server
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    user: "1001:1001"
    environment:
      - PASSWORD=123456
      - CODE_SERVER_BASE_PATH=/code
    volumes:
      - ./nextcloud/html/data/codeuser:/home/coder
      - ./code-server/config:/home/coder/.config/code-server
    networks:
      - app-network
    restart: unless-stopped
    command: --bind-addr 0.0.0.0:8080

  # Nextcloud
  nextcloud:
    ports:
    - "8022:80"
    image: nextcloud:latest
    container_name: nextcloud
    volumes:
      - ./nextcloud/html:/var/www/html
    networks:
      - app-network
    restart: unless-stopped

  # Nginx（反向代理）
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  # 配置文件挂载到容器内
      - ./nginx/ssl:/etc/nginx/ssl  # SSL 证书目录挂载
      - ./nginx/html:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - code-server
      - nextcloud
    restart: unless-stopped

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=123456
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
